from django.urls import path
from .views import *

urlpatterns = [
    path('admin-login/', admin_login_api),
    path('add-category/', add_category),
    path('manage-category/', list_category),
    path('category-details/<int:id>/', category_detail),
    path('dashboard-metrics/', dashboard_metrics),
    path('monthly-sales-summary/', monthly_sales_summary),
    path('weekly-sales-summary/', weekly_sales_summary),
    path('weekly-user-registrations/', weekly_user_registrations),
    path('top-selling-foods/', top_selling_foods),


    path('add-food/', add_food),
    path('manage-foods/', list_foods),
    path('delete-food/<int:id>/', delete_food),
    path('edit-food/<int:id>/', edit_food),
    path('food_search/', food_search),
    path('random_foods/', random_foods),
    path('register/', register_user),
    path('login/', login_user),
    path('foods/<int:id>/', food_detail),
    path('cart/add/', add_to_cart),
    path('cart/<int:user_id>/', cart_items),
    path('cart/update_quantity/', update_cart),
    path('cart/remove_cart_item/<int:order_id>/', delete_cart_item),
    path('place_order/', place_order),
    path('orders/<int:user_id>/', user_orders),
    path('track-order/<str:order_number>/', track_order),
    path('cancel-order/<str:order_number>/', cancel_order),
    path('orders/by_order_number/<str:order_number>/', order_details),
    path('orders/order_address/<str:order_number>/', get_order_address),
    path('invoice/<str:order_number>/', get_invoice),
    path('user/<int:user_id>/', get_user_profile),
    path('user/update/<int:user_id>/', update_user_profile),
    path('change_password/<int:user_id>/', change_password),
    path('orders-not-confirmed/', orders_not_confirmed),
    path('orders-confirmed/', orders_confirmed),
    path('food_being_prepared/', food_being_prepared),
    path('foodpickup/', food_pickup),
    path('orders-delivered/', food_delivered),
    path('order-cancelled/', order_cancelled),
    path('all-foods/', all_orders),
    path('order-between-dates/', order_reports),
    path('view-order-detail/<str:order_number>/', view_order_detail),
    path('update-order-status/', update_order_status),
    path('search-orders/', search_orders),
    path('users/', list_users),
    path('delete-user/<int:id>/', delete_user),
    path('wishlist/add/', add_to_wishlist),
    path('wishlist/remove/', remove_from_wishlist),
    path('wishlist/<int:user_id>/', get_wishlist),
    path('reviews/add/<int:food_id>/', add_review),
    path('reviews/<int:food_id>/', food_reviews),
    path('review-edit-delete/<int:id>/', manage_reviews),
    path('food-rating/<int:food_id>/', food_rating_summary),
    path('all-reviews/', all_reviews),
    path('delete-reviews/<int:id>/', delete_review),
]