# Generated by Django 5.1.7 on 2026-05-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0005_alter_paymentdetail_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
