# Generated by Django 5.1.7 on 2026-06-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0006_alter_paymentdetail_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='paymentdetail',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='paymentdetail',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='payment_status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='stripe_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
