# Generated by Django 5.1.7 on 2026-06-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0007_remove_paymentdetail_card_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='paymentdetail',
            name='stripe_payment_id',
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='cvv',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='expiry_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
