# Generated by Django 5.1.7 on 2026-06-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0008_remove_paymentdetail_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
